//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Installer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Installer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE DATABASE [mastercafedb];
        ///.
        /// </summary>
        internal static string create {
            get {
                return ResourceManager.GetString("create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE [mastercafedb];
        ///EXEC dbo.sp_dbcmptlevel @dbname=N&apos;mastercafedb&apos;, @new_cmptlevel=90;
        ///ALTER DATABASE [mastercafedb] SET ANSI_NULL_DEFAULT OFF;
        ///ALTER DATABASE [mastercafedb] SET ANSI_NULLS OFF;
        ///ALTER DATABASE [mastercafedb] SET ANSI_PADDING OFF; 
        ///ALTER DATABASE [mastercafedb] SET ANSI_WARNINGS OFF;
        ///ALTER DATABASE [mastercafedb] SET ARITHABORT OFF;
        ///ALTER DATABASE [mastercafedb] SET AUTO_CLOSE OFF;
        ///ALTER DATABASE [mastercafedb] SET AUTO_CREATE_STATISTICS ON;
        ///ALTER DATABASE [mastercafedb] SET AUTO_SH [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dbcfg {
            get {
                return ResourceManager.GetString("dbcfg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE [mastercafedb];
        ///SET ANSI_NULLS ON;
        ///SET QUOTED_IDENTIFIER ON;
        ///CREATE TABLE [dbo].[member](
        ///	[name] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
        ///	[password] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
        ///	[stock] [int] NOT NULL,
        ///	[ot] [smalldatetime] NOT NULL,
        /// CONSTRAINT [PK_member_1] PRIMARY KEY CLUSTERED 
        ///(
        ///	[name] ASC
        ///)WITH (PAD_INDEX  = OFF, IGNORE_DUP_KEY = OFF) ON [PRIMARY]
        ///) ON [PRIMARY];
        ///SET ANSI_NULLS ON;
        ///SET QUOTED_IDENTIFIER ON;
        ///CREATE TABLE [dbo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string generate {
            get {
                return ResourceManager.GetString("generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_1007767 {
            get {
                object obj = ResourceManager.GetObject("image_1007767", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE [mastercafedb];
        ///insert into employee values(&apos;admin&apos;,&apos;CgAAAB+LCAAAAAAABADtvQdgHEmWJSYvbcp7f0r1StfgdKEIgGATJNiQQBDswYjN5pLsHWlHIymrKoHKZVZlXWYWQMztnbz33nvvvffee++997o7nU4n99//P1xmZAFs9s5K2smeIYCqyB8/fnwfPyIWWdPm9TQ7z/8fUJ2hAwoAAAA=&apos;,1);.
        /// </summary>
        internal static string insert {
            get {
                return ResourceManager.GetString("insert", resourceCulture);
            }
        }
    }
}
